### ISSUE TITLE
Typo in JSON-LD context

### ISSUE THREAD

**Issue by brechtvdv** [Informatievlaanderen/OSLOthema-cultureelErfgoed#12]
The Event AP has a typo in the @id field of "Toekenning.toegekendAttribuut: 
```
"Toekenning.toegekendAttribuut": {
      "@container": "@set",
      "@id": " http://www.cidoc-crm.org/cidoc-crm/P177_assigned_property_type",
      "@type": "http://www.w3.org/2001/XMLSchema#anyURI"
    }
```
As you can see, there is a space before the URI value of http://www.cidoc-crm.org/cidoc-crm/P177_assigned_property_type.
This gives following syntax error in jsonld-parser:
jsonld.SyntaxError: Invalid JSON-LD syntax; a @context @id value must be an absolute IRI, a blank node identifier, or a keyword.

**Comment by bertvannuffelen** [comment]
Kan je de EAP file checken. Ik vermoed dat de URI een spatie bevat. Want ook de html pagina heeft dat als naar de source kijkt.

**Comment by brechtvdv** [comment]
Ik bevestig dat er een spatie in zit

**Comment by brechtvdv** [comment]
Nu is dit kapot:
Toekenning.toegekendAttribuut: {
@container: "@set",
@id: "https://wherever/TODO",
@type: ""
},

**Comment by mvanbrab** [comment]
Tiens, in deze JSON-LD file https://test.data.vlaanderen.be/doc/applicatieprofiel/cultureel-erfgoed-event/kandidaatstandaard/2020-09-30/context/cultureel-erfgoed-event-ap.jsonld,
te vinden via de link in https://test.data.vlaanderen.be/doc/applicatieprofiel/cultureel-erfgoed-event/, spec die ik corrigeerde, staat:
 ```
    "Toekenning.toegekendAttribuut": {
      "@container": "@set",
      "@id": "http://www.cidoc-crm.org/cidoc-crm/P177_assigned_property_type",
      "@type": "http://www.w3.org/2001/XMLSchema#anyURI"
    },
```

Ik zie wel dat deze versie nog niet op productie staat; daar staat nog de oude versie, waarin jouw oorspronkelijke gemelde fout (de spatie voor de URI) nog staat. Die transfer naar productie moet dus nog gebeuren. Ik assigneer even aan Bert.
