### ISSUE TITLE
Kardinaliteiten aanpassen

### ISSUE THREAD

**Issue by brechtvdv** [Informatievlaanderen/OSLOthema-cultureelErfgoed#13]
Bij Mensgemaakt Object:
- materiaal [1]
Een mensgemaakt object bestaat meestal uit meerdere materialen,
bijvoorbeeld: een popje kan bestaan uit "textiel" en "kunststof".
Ik zou dit aanpassen naar [0..*].
 
- locatie [1]
- permanente locatie [1]
Ter discussie of dit gewenste kardinaliteiten zijn voor musea.
De locatie-historiek is soms aanwezig, maar niet altijd. De huidige locatie kan dus niet altijd uitgewisseld worden.
De permanente locatie is veelal een interne code van het depot.

**Comment by dimi-schepers** [comment]
Locatie en permanente locatie kunnen we optioneel maken; dit is ook het geval bij CIDOC, zie:
- http://www.cidoc-crm.org/cidoc-crm/P55_has_current_location
- http://www.cidoc-crm.org/cidoc-crm/P54_has_current_permanent_location

Voor materiaal kunnen we de maximumkardinaliteit veranderen naar _many_ (is ook het geval bij CIDOC), maar de minimumkardinaliteit houden we best wel op 1 (dus [1..*]), om gealigneerd te blijven met CIDOC, zie: 
- http://www.cidoc-crm.org/cidoc-crm/P45_consists_of

**Comment by jitsedc** [comment]
https://data.vlaanderen.be/doc/applicatieprofiel/cultureel-erfgoed-object/#MensgemaaktObject
