### ISSUE TITLE
Verwijzen naar deel van een object

### ISSUE THREAD

**Issue by brechtvdv** [Informatievlaanderen/OSLOthema-cultureelErfgoed#14]
Ik zou graag (fysieke) delen van een object beschrijven, bijvoorbeeld:
een MensgemaaktObject "strijkijzer" is gemaakt uit verschillende materialen.
De stekker is van materiaal X, het handvat is van materiaal Y...

Dit is anders dan bij bv. het Lam Gods dat via een Complex Werk meerdere werken kan omvatten.

Het datatype "Beschrijving" zou hier eventueel voor gebruikt kunnen worden?
https://data.vlaanderen.be/ns/cultureel-erfgoed#Beschrijving

**Comment by brechtvdv** [comment]
Zelfde probleem met een Dimensie specifiëren over een bepaalde deel van een object

**Comment by dimi-schepers** [comment]
Dit zou volgens ons er al moeten inzitten: zie https://data.vlaanderen.be/doc/applicatieprofiel/cultureel-erfgoed-object#Materieel%20Ding%3Abestaat%20uit ?

**Comment by brechtvdv** [comment]
Klopt! Over het hoofd gezien!
