### ISSUE TITLE
"has symbolic content" bij Taalobject 

### ISSUE THREAD

**Issue by brechtvdv** [Informatievlaanderen/OSLOthema-cultureelErfgoed#16]
Om een inscriptie (de tekst) op een poster bv. te beschrijven kan het Taalobject gebruikt worden.

Maar het attribuut om dit toe te voegen kan momenteel enkel met "Entiteit.beschrijving".
In de CIDOC-CRM wereld en meer specifiek Linked Art gebruikt men volgende, recente eigenschap: "P190_has_symbolic_content".
Zie voorbeeldjes met "content" als attribuut: https://linked.art/model/document/#physical-objects-conceptual-texts
Bij Van Gogh world wide wordt dit ook gebruikt: https://github.com/vangoghworldwide/linkedart#inscriptions

Het lijkt me dus een must-have om dit attribuut toe te voegen bij Taalobject om zo in lijn te zijn met Linked Art en CIDOC.

**Comment by dimi-schepers** [comment]
Voorstel om het attribuut "inhoud" (http://www.cidoc-crm.org/cidoc-crm/P190_has_symbolic_content) toe te voegen op de klasse Taalobject met "String" als range en [0..*] als kardinaliteit.

(Merk op: deze property resolvet niet want is pas ingevoerd in versie 6.2.5, na de officiële versie 5.0.5.)

**Comment by GeertThijs** [comment]
Oké, maar door dat te doen wordt de suggestie gewekt dat dit in CIDOC een attribuut is van Taalobject, wat niet het geval is. P190 is een attribuut van E90 SymbolicObject, een object dat we uit het model hebben weggelaten (herinner dat we uit CIDOC "geshopt" hebben omwille van de complexiteit). E90 SymbolicObject toevoegen kan zomaar niet en zeker niet voor dat ene attribuut. Het zit tussen E28 ConceptualObject (ConceptueelDing) en E73 InformationObject (Informatieobject). Het attribuut zou dus al zeker een niveau hoger moeten en geldt dan ook voor andere Informatieobjecten ttz ZelfstandigeExpressie, OntwerpOfProcedure, VisueelItem & Document. Aangezien de enige andere subklasse van E90 SymbolicObject  E41 Appelation is en we deze klasse hebben weggelaten is hoogstens deze oplossing aanvaardbaar: P190 toevoegen aan Informatieobject.

**Comment by jitsedc** [comment]
https://data.vlaanderen.be/doc/applicatieprofiel/cultureel-erfgoed-object/#InformatieObject
