### ISSUE TITLE
probleem met domein, url

### ISSUE THREAD

**Issue by gossele** [Informatievlaanderen/OSLOthema-cultureelErfgoed#18]
Configuratefout of kaping?
[https://www.realtime.at/gecatcht/#iri=https://data.vlaanderen.be/ns/cultureel-erfgoed.ttl](url)
![domeinnaamerfgoedissue](https://user-images.githubusercontent.com/11721629/175774188-53166af0-7a41-4090-993a-66b971baebfc.jpg)

Tekst die getoond wordt:
<html>
<body>
<h2 style="font-family: Tahoma, Calibri, Verdana, Geneva, sans-serif; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: -webkit-center; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Diese Domain wurde erfolgreich für einen Kunden von</h2><h2 style="font-family: Tahoma, Calibri, Verdana, Geneva, sans-serif; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: -webkit-center; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><img border="0" src="https://www.realtime.at/gecatcht/logo.png" width="500" height="138"></h2><h2 style="font-family: Tahoma, Calibri, Verdana, Geneva, sans-serif; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: -webkit-center; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">gecatcht!</h2><hr style="color: rgb(0, 0, 0); font-family: Tahoma, Calibri, Verdana, Geneva, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: -webkit-center; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; width: 1752.8px;">

Sie interessieren sich auch für gecatchte Domains?Hier gehts zu unserem Backorder-System | Wir unterstützen derzeit folgende Endungen:.AT (Österreich).BE (Belgien).CH (Schweiz).DE (Deutschland).EU (Europäische Union).LI (Liechtenstein)
-- | --

<br class="Apple-interchange-newline">
</body>
</html>Diese Domain wurde erfolgreich für einen Kunden von

gecatcht!
Sie interessieren sich auch für gecatchte Domains?

[Hier gehts zu unserem Backorder-System](https://www.realtime.at/)
Wir unterstützen derzeit folgende Endungen:
.AT (Österreich)
.BE (Belgien)
.CH (Schweiz)
.DE (Deutschland)
.EU (Europäische Union)
.LI (Liechtenstein)

**Comment by jitsedc** [comment]
[Terug live](https://data.vlaanderen.be/ns/cultureel-erfgoed.ttl)
