### ISSUE TITLE
Use-cases voor Onroerend Erfgoed

### ISSUE THREAD

**Issue by koenedaele** [Informatievlaanderen/OSLOthema-cultureelErfgoed#4]
Ik heb snel een aantal mogelijke use-cases voor Onroerend Erfgoed opgesteld. Ik heb getracht links op te nemen naar relevante webpagina's zonder onze volledige website te gaan opsommen.

1. Als eigenaar van een onroerend goed (een woning, een handelspand, een industrieel pand, een stuk land, ...) wil ik weten welke rechtsgevolgen aan mijn onroerend goed gekoppeld zijn.
2. Als notaris of vastgoedmakelaar wens ik de rechtsgevolgen van een onroerend goed betrokken in een transactie te kennen (https://www.onroerenderfgoed.be/informatie-en-meldingsplicht-bij-eigendomsoverdracht).
3. Als burger, heemkundige of onderzoeker wil ik meer weten over de materiële resten van het verleden in Vlaanderen. Ik wil alle barokke kerken in mijn provincie of gemeente kunnen vinden. Ik wil weten welke opgravingen er in de jaren '80 in mijn omgeving plaats vonden.
4. Als Vlaams Architectuur Archief (VAI) wil ik archiefbeschrijvingen van archieven van architecten kunnen koppelen aan de realisaties van deze architect die gekend zijn in de inventaris onroerend erfgoed (https://www.onroerenderfgoed.be/nieuws/collectie-vai-gekoppeld-aan-onze-inventaris).
5. Als agentschap Onroerend Erfgoed of Intergemeentelijke Onroerend Erfgoed Dienst wil weten welke toelatingen, adviezen en premies er in het verleden werden uitgereikt voor een onroerend goed.
6. Als burger, projectontwikkelaar of makelaar wil ik weten of een bepaald perceel aanleiding zal geven tot het opstellen van een archeologienota. (https://www.onroerenderfgoed.be/archeologie-bij-vergunningsaanvragen-bouwheren)
7. Als metaaldetectorist moet ik mijn vondsten melden bij het agentschap Onroerend Erfgoed zoals beschreven in het onroerend erfgoed decreet (https://www.onroerenderfgoed.be/ik-ben-metaaldetectorist).
8. Als metaaldetectorist wil ik mijn vondsten op een makkelijke manier kunnen melden bij zowel MEDEA (https://medea-cms.weopendata.com/) als Onroerend Erfgoed.
9. Als burger of onderzoeker wil ik documentatie over onroerend erfgoed in de vorm van afbeeldingen, teksten, kaarten, bibliografiën of andere informatiebronnen kunnen raadplegen.
10. Als burger wil ik de status van mijn toelatings- (https://www.onroerenderfgoed.be/ik-wil-werken-uitvoeren-aan-erfgoed) of premieaanvraag (https://www.onroerenderfgoed.be/ik-wil-financiele-ondersteuning-krijgen) kunnen raadplegen bij de behandelende overheid.
11. Als informatiebeheerder wil ik alle dossiers in mijn archief over een bepaald onroerend erfgoed (een kerk, een standbeeld, een brug, een woning, een boom, een pompstation, een boot, een motte, een bunker, een sluis, een rivervallei, ...) kunnen terugvinden, ook al zitten die in verschillende reeksen.
12. Als onderzoeker, collectiebeheerder of overheid wil ik weten welke topstukken er in een bepaald onroerend erfgoed aanwezig zijn (en vice versa)
13. Als onderzoeker of collectiebeheerder wil ik weten in welk onroerenderfgoeddepot (https://www.onroerenderfgoed.be/ik-werk-voor-een-onroerenderfgoeddepot) het archeologische ensemble (de vondsten en de documentatie ) van een bepaald archeologisch onderzoek zich bevinden.
14. Als omgevingsloket wil ik een omgevingsaanvraag voor advies voorleggen aan onroerend erfgoed indien het om beschermd erfgoed gaat.
15. Als Vlaamse overheid wil ik de laag van het beschermde erfgoed kunnen publiceren in het INSPIRE protected sites thema.

**Comment by dimi-schepers** [comment]
Een overzicht van in scope, voorlopig out-of-scope (eventueel voor een versie 2 van de standaard) en out-of-scope use cases kan [hier](https://github.com/Informatievlaanderen/OSLOthema-cultureelErfgoed/blob/master/resources/useCases.md) geraadpleegd worden.
