### ISSUE TITLE
Titels en beschrijvingen van Collecties

### ISSUE THREAD

**Issue by koenedaele** [Informatievlaanderen/OSLOthema-cultureelErfgoed#8]
Versie: Object AP | 2020-07-02

Inheritance: Gecureerde Collectie -> Collectie -> Entiteit

Gecureerde Collectie heeft een titel (TaalString 0..*). Collectie heeft dit niet, terwijl een titel kunnen geven aan een collectie ook interessant is, anders is een collectie een heel abstract iets.

Zowel Gecureerde Collectie als Collectie erven over van Entiteit. Die heeft geen titel, maar wel een beschrijving (TaalString 0..*). Is het verschil tussen titel en beschrijving het verschil tussen dc:title en dc:description? Een korte titel en een uitgebreide beschrijving?

Er is ook een datatype Beschrijving, maar dat wordt niet gebruik voor Entiteit.beschrijving?

Waarom zit Titel niet gewoon bij Entiteit zodat ook Collectie die kan gebruiken?

**Comment by brechtvdv** [comment]
Zelfde probleem bij Collectie van de Gentenaar waar we ook graag titel willen gebruiken op Collectie.
Momenteel gebruik ik beschrijving hiervoor.

Datatype beschrijving wordt momenteel niet gebruikt zie ik. Waarschijnlijk was dit bedoeld als eigenschap bij MensgemaaktKenmerk?

**Comment by dimi-schepers** [comment]
We stellen voor om dcterms:title toe te voegen op Collectie.

**Comment by GeertThijs** [comment]
GecureerdeCollectie is gedefinieerd als subklasse van Collectie, als we titel als attribuut toevoegen aan Collectie erft GecureerdeCollectie deze over (terwijl het al een titel heeft). Enige oplossing die daar momenteel voor bestaat is het toevoegen van  het predicaat {redefine titel} bij GecureerdeCollectie.titel. Hoe dan ook, als we de kardinaliteit op 0..* laten staan in beide gevallen (een Collectie heeft niet altijd een titel of kan er ook meerdere hebben) is er in praktijk alvast niet de verplichting om twee titels mee te geven.

**Comment by jitsedc** [comment]
https://data.vlaanderen.be/doc/applicatieprofiel/cultureel-erfgoed-object/#Collectie
